# -------------------------------------------------------------------
# Site Settings
# -------------------------------------------------------------------
title: "RPlayer III â€” Minimal Audio Stream Controller"
description: "Lightweight utility for controlling audio streams, with zero dependencies. Perfect for extensions and modern web apps."
lang: "en"
timezone: "America/Toronto"
url: "https://rplayer.js.org"
baseurl: ""

# SEO
author: "David Landry"

# -------------------------------------------------------------------
# Build Settings
# -------------------------------------------------------------------
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from sitemap
defaults:
  - scope:
      path: "404.html"
    values:
      sitemap: false
  - scope:
      path: "googlef84e2477d307cfb8.html"
    values:
      sitemap: false

# -------------------------------------------------------------------
# File Management
# -------------------------------------------------------------------

# Force Jekyll to include these files/folders in the build
include:
  - images/
  - scripts.js
  - styles.css
  - CNAME

# Prevent Jekyll from reading or publishing these development files
exclude:
  - dist/
  - src/
  - types/
  - .gitignore
  - .github/
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - vite.config.js
  - node_modules/
